/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CrashRouteImport } from './routes/crash'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as ElectivesRouteImport } from './routes/electives'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as TracksIndexRouteImport } from './routes/tracks.index'
import { Route as TracksIdRouteImport } from './routes/tracks.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CrashRoute = CrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectivesRoute = ElectivesRouteImport.update({
  id: '/electives',
  path: '/electives',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TracksRoute,
} as any)
const TracksIdRoute = TracksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TracksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/crash': typeof CrashRoute
  '/curriculum': typeof CurriculumRoute
  '/electives': typeof ElectivesRoute
  '/roadmap': typeof RoadmapRoute
  '/skills': typeof SkillsRoute
  '/tracks': typeof TracksRouteWithChildren
  '/companies/$id': typeof CompaniesIdRoute
  '/tracks/$id': typeof TracksIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/crash': typeof CrashRoute
  '/curriculum': typeof CurriculumRoute
  '/electives': typeof ElectivesRoute
  '/roadmap': typeof RoadmapRoute
  '/skills': typeof SkillsRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/tracks/$id': typeof TracksIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/tracks': typeof TracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/crash': typeof CrashRoute
  '/curriculum': typeof CurriculumRoute
  '/electives': typeof ElectivesRoute
  '/roadmap': typeof RoadmapRoute
  '/skills': typeof SkillsRoute
  '/tracks': typeof TracksRouteWithChildren
  '/companies/$id': typeof CompaniesIdRoute
  '/tracks/$id': typeof TracksIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/companies'
    | '/crash'
    | '/curriculum'
    | '/electives'
    | '/roadmap'
    | '/skills'
    | '/tracks'
    | '/companies/$id'
    | '/tracks/$id'
    | '/companies/'
    | '/tracks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/crash'
    | '/curriculum'
    | '/electives'
    | '/roadmap'
    | '/skills'
    | '/companies/$id'
    | '/tracks/$id'
    | '/companies'
    | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/companies'
    | '/crash'
    | '/curriculum'
    | '/electives'
    | '/roadmap'
    | '/skills'
    | '/tracks'
    | '/companies/$id'
    | '/tracks/$id'
    | '/companies/'
    | '/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  CrashRoute: typeof CrashRoute
  CurriculumRoute: typeof CurriculumRoute
  ElectivesRoute: typeof ElectivesRoute
  RoadmapRoute: typeof RoadmapRoute
  SkillsRoute: typeof SkillsRoute
  TracksRoute: typeof TracksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crash': {
      id: '/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof CrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electives': {
      id: '/electives'
      path: '/electives'
      fullPath: '/electives'
      preLoaderRoute: typeof ElectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof TracksRoute
    }
    '/tracks/$id': {
      id: '/tracks/$id'
      path: '/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof TracksIdRouteImport
      parentRoute: typeof TracksRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface TracksRouteChildren {
  TracksIdRoute: typeof TracksIdRoute
  TracksIndexRoute: typeof TracksIndexRoute
}

const TracksRouteChildren: TracksRouteChildren = {
  TracksIdRoute: TracksIdRoute,
  TracksIndexRoute: TracksIndexRoute,
}

const TracksRouteWithChildren =
  TracksRoute._addFileChildren(TracksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  CrashRoute: CrashRoute,
  CurriculumRoute: CurriculumRoute,
  ElectivesRoute: ElectivesRoute,
  RoadmapRoute: RoadmapRoute,
  SkillsRoute: SkillsRoute,
  TracksRoute: TracksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
